[package]
name = "pixelctl"
version = "0.1.0"
authors = ["Michael Williams <michael.williams@enspiral.com>"]

[dependencies]
kiss3d = "0.13"
env_logger = "0.5.3"
fps_clock = "2.0"
glfw = "0.19"
log = "0.4"
modulo = "0.1.2"
nalgebra = "0.14"
rayon = "1.0.0"
